language: objective-c
osx_image: xcode7
script: set -e && xcodebuild -project BowieUtilityKnife.xcworkspace -scheme BowieUtilityKnifeTests test -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -destination 'platform=iOS Simulator,name=iPhone 6 Plus' | xcpretty -c
